spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pruebadb?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: mortem45
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
